In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries loaded successfully")

Libraries loaded successfully

In [2]:
FILE_PATH = r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\analysis.xlsx"

analysis_raw = pd.read_excel(
    FILE_PATH,
    sheet_name="Analysis",
    header=1
)

print("Shape:", analysis_raw.shape)
print("\nColumns:")
print(analysis_raw.columns.tolist())

Shape: (20, 6)

Columns:
['id', 'company_id', 'compounded_sales_growth', 'compounded_profit_growth', 'stock_price_cagr', 'roe']

In [3]:
display(analysis_raw.head(10))

,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
0,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
1,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
2,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
3,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%
4,13,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%
5,14,TCS,5 Years: 10%,5 Years: 8%,5 Years: 16%,5 Years: 44%
6,15,TCS,3 Years: 14%,3 Years: 12%,3 Years: 8%,3 Years: 47%
7,16,TCS,TTM: 5%,TTM: 8%,1 Year: 16%,Last Year: 52%
8,17,WIPRO,10 Years: 8%,10 Years: 3%,10 Years: 12%,10 Years: 18%
9,18,WIPRO,5 Years: 9%,5 Years: 4%,5 Years: 20%,5 Years: 17%

In [4]:
analysis_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        20 non-null     int64
 1   company_id                20 non-null     object
 2   compounded_sales_growth   20 non-null     object
 3   compounded_profit_growth  20 non-null     object
 4   stock_price_cagr          20 non-null     object
 5   roe                       20 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.1+ KB

In [5]:
missing_report = pd.DataFrame({
    "missing_count": analysis_raw.isna().sum(),
    "missing_pct": analysis_raw.isna().mean() * 100
})

missing_report.sort_values(
    "missing_count",
    ascending=False
)

                          missing_count  missing_pct
id                                    0          0.0
company_id                            0          0.0
compounded_sales_growth               0          0.0
compounded_profit_growth              0          0.0
stock_price_cagr                      0          0.0
roe                                   0          0.0

In [6]:
print(
    "Duplicate IDs:",
    analysis_raw["id"].duplicated().sum()
)

print(
    "Duplicate company IDs:",
    analysis_raw["company_id"].duplicated().sum()
)

Duplicate IDs: 0
Duplicate company IDs: 15

In [7]:
analysis_raw["company_id"].value_counts()

company_id
HDFCBANK    4
SBILIFE     4
TCS         4
WIPRO       4
INFY        4
Name: count, dtype: int64

In [8]:
analysis_raw[
    ["id", "company_id", "compounded_sales_growth",
     "compounded_profit_growth", "stock_price_cagr", "roe"]
]

,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
0,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
1,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
2,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
3,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%
4,13,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%
5,14,TCS,5 Years: 10%,5 Years: 8%,5 Years: 16%,5 Years: 44%
6,15,TCS,3 Years: 14%,3 Years: 12%,3 Years: 8%,3 Years: 47%
7,16,TCS,TTM: 5%,TTM: 8%,1 Year: 16%,Last Year: 52%
8,17,WIPRO,10 Years: 8%,10 Years: 3%,10 Years: 12%,10 Years: 18%
9,18,WIPRO,5 Years: 9%,5 Years: 4%,5 Years: 20%,5 Years: 17%
10,19,WIPRO,3 Years: 13%,3 Years: 0%,3 Years: -1%,3 Years: 17%
11,2,HDFCBANK,5 Years: 22%,5 Years: 23%,5 Years: 8%,5 Years: 17%
12,20,WIPRO,TTM: -3%,TTM: 1%,1 Year: 39%,Last Year: 14%
13,3,HDFCBANK,3 Years: 30%,3 Years: 26%,3 Years: 8%,3 Years: 17%
14,4,HDFCBANK,TTM: 47%,TTM: 27%,1 Year: 13%,Last Year: 17%
15,5,INFY,10 Years: 12%,10 Years: 9%,10 Years: 15%,10 Years: 27%
16,6,INFY,5 Years: 13%,5 Years: 11%,5 Years: 22%,5 Years: 29%
17,7,INFY,3 Years: 5%,3 Years: 10%,3 Years: 4%,3 Years: 31%
18,8,INFY,TTM: 3%,TTM: 8%,1 Year: 27%,Last Year: 32%
19,9,SBILIFE,10 Years: 23%,10 Years: 9%,10 Years: 9%,10 Years: 16%

In [9]:
def parse_metric(value):
    """
    Convert values such as:
    '10 Years: 21%'
    '5 Years: 24%'
    'TTM: 43%'
    'Last Year: 12%'

    into:
    period, numeric_value
    """

    if pd.isna(value):
        return pd.Series([np.nan, np.nan])

    value = str(value).strip()

    if ":" not in value:
        return pd.Series([np.nan, np.nan])

    period, percentage = value.split(":", 1)

    period = period.strip()
    percentage = percentage.strip().replace("%", "")

    try:
        numeric_value = float(percentage)
    except ValueError:
        numeric_value = np.nan

    return pd.Series([period, numeric_value])

In [10]:
test_values = [
    "10 Years: 21%",
    "5 Years: 24%",
    "3 Years: 17%",
    "TTM: 43%",
    "Last Year: 12%"
]

for value in test_values:
    print(value, "→", parse_metric(value).tolist())

10 Years: 21% → ['10 Years', 21.0]
5 Years: 24% → ['5 Years', 24.0]
3 Years: 17% → ['3 Years', 17.0]
TTM: 43% → ['TTM', 43.0]
Last Year: 12% → ['Last Year', 12.0]

In [11]:
metrics = [
    "compounded_sales_growth",
    "compounded_profit_growth",
    "stock_price_cagr",
    "roe"
]

for column in metrics:

    parsed = analysis_raw[column].apply(parse_metric)

    analysis_raw[column + "_period"] = parsed[0]
    analysis_raw[column + "_value"] = parsed[1]

In [12]:
analysis_raw.head()

,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe,compounded_sales_growth_period,compounded_sales_growth_value,compounded_profit_growth_period,compounded_profit_growth_value,stock_price_cagr_period,stock_price_cagr_value,roe_period,roe_value
0,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%,10 Years,21.0,10 Years,22.0,10 Years,15.0,10 Years,17.0
1,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%,5 Years,24.0,5 Years,6.0,5 Years,8.0,NaN,NaN
2,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%,3 Years,17.0,3 Years,9.0,3 Years,7.0,3 Years,13.0
3,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%,TTM,43.0,TTM,18.0,1 Year,-2.0,Last Year,12.0
4,13,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%,10 Years,11.0,10 Years,9.0,10 Years,14.0,10 Years,40.0

In [13]:
def parse_metric(value):
    if pd.isna(value):
        return pd.Series([np.nan, np.nan])

    value = str(value).strip()

    # Handle both "10 Years: 21%" and "5 Years 14%"
    if ":" in value:
        period, percentage = value.split(":", 1)
    else:
        # Split at the last space before the percentage
        parts = value.rsplit(" ", 1)

        if len(parts) != 2:
            return pd.Series([np.nan, np.nan])

        period, percentage = parts

    period = period.strip()
    percentage = percentage.strip().replace("%", "")

    try:
        numeric_value = float(percentage)
    except ValueError:
        numeric_value = np.nan

    return pd.Series([period, numeric_value])

In [14]:
metrics = [
    "compounded_sales_growth",
    "compounded_profit_growth",
    "stock_price_cagr",
    "roe"
]

for column in metrics:
    parsed = analysis_raw[column].apply(parse_metric)

    analysis_raw[column + "_period"] = parsed[0]
    analysis_raw[column + "_value"] = parsed[1]

In [15]:
analysis_raw[
    [
        "company_id",
        "roe",
        "roe_period",
        "roe_value"
    ]
]

   company_id                    roe roe_period  roe_value
0    HDFCBANK      10 Years:     17%   10 Years       17.0
1     SBILIFE   5 Years          14%    5 Years       14.0
2     SBILIFE   3 Years:         13%    3 Years       13.0
3     SBILIFE    Last Year:      12%  Last Year       12.0
4         TCS    10 Years:       40%   10 Years       40.0
5         TCS  5 Years:          44%    5 Years       44.0
6         TCS  3 Years:          47%    3 Years       47.0
7         TCS   Last Year:       52%  Last Year       52.0
8       WIPRO   10 Years:        18%   10 Years       18.0
9       WIPRO  5 Years:          17%    5 Years       17.0
10      WIPRO  3 Years:          17%    3 Years       17.0
11   HDFCBANK     5 Years:       17%    5 Years       17.0
12      WIPRO   Last Year:       14%  Last Year       14.0
13   HDFCBANK     3 Years:       17%    3 Years       17.0
14   HDFCBANK      Last Year:    17%  Last Year       17.0
15       INFY     10 Years:      27%   10 Years       27.0
16       INFY    5 Years:        29%    5 Years       29.0
17       INFY    3 Years:        31%    3 Years       31.0
18       INFY     Last Year:     32%  Last Year       32.0
19    SBILIFE     10 Years:      16%   10 Years       16.0

In [16]:
for metric in metrics:

    value_col = metric + "_value"

    print(
        metric,
        "failed parsing:",
        analysis_raw[value_col].isna().sum()
    )

compounded_sales_growth failed parsing: 0
compounded_profit_growth failed parsing: 0
stock_price_cagr failed parsing: 0
roe failed parsing: 0

In [17]:
for metric in metrics:

    period_col = metric + "_period"

    print(f"\n{metric}")
    print(analysis_raw[period_col].value_counts())

compounded_sales_growth
compounded_sales_growth_period
10 Years    5
5 Years     5
3 Years     5
TTM         5
Name: count, dtype: int64

compounded_profit_growth
compounded_profit_growth_period
10 Years    5
5 Years     5
3 Years     5
TTM         5
Name: count, dtype: int64

stock_price_cagr
stock_price_cagr_period
10 Years    5
5 Years     5
3 Years     5
1 Year      5
Name: count, dtype: int64

roe
roe_period
10 Years     5
5 Years      5
3 Years      5
Last Year    5
Name: count, dtype: int64

In [18]:
analysis_clean = analysis_raw[
    [
        "id",
        "company_id",

        "compounded_sales_growth_period",
        "compounded_sales_growth_value",

        "compounded_profit_growth_period",
        "compounded_profit_growth_value",

        "stock_price_cagr_period",
        "stock_price_cagr_value",

        "roe_period",
        "roe_value"
    ]
].copy()

In [19]:
analysis_clean = pd.DataFrame({
    "id": analysis_raw["id"],
    "company_id": analysis_raw["company_id"],

    "sales_growth_period": analysis_raw["compounded_sales_growth_period"],
    "sales_growth": analysis_raw["compounded_sales_growth_value"],

    "profit_growth_period": analysis_raw["compounded_profit_growth_period"],
    "profit_growth": analysis_raw["compounded_profit_growth_value"],

    "stock_price_cagr_period": analysis_raw["stock_price_cagr_period"],
    "stock_price_cagr": analysis_raw["stock_price_cagr_value"],

    "roe_period": analysis_raw["roe_period"],
    "roe": analysis_raw["roe_value"]
})

print("Shape:", analysis_clean.shape)
display(analysis_clean)

Shape: (20, 10)

,id,company_id,sales_growth_period,sales_growth,profit_growth_period,profit_growth,stock_price_cagr_period,stock_price_cagr,roe_period,roe
0,1,HDFCBANK,10 Years,21.0,10 Years,22.0,10 Years,15.0,10 Years,17.0
1,10,SBILIFE,5 Years,24.0,5 Years,6.0,5 Years,8.0,5 Years,14.0
2,11,SBILIFE,3 Years,17.0,3 Years,9.0,3 Years,7.0,3 Years,13.0
3,12,SBILIFE,TTM,43.0,TTM,18.0,1 Year,-2.0,Last Year,12.0
4,13,TCS,10 Years,11.0,10 Years,9.0,10 Years,14.0,10 Years,40.0
5,14,TCS,5 Years,10.0,5 Years,8.0,5 Years,16.0,5 Years,44.0
6,15,TCS,3 Years,14.0,3 Years,12.0,3 Years,8.0,3 Years,47.0
7,16,TCS,TTM,5.0,TTM,8.0,1 Year,16.0,Last Year,52.0
8,17,WIPRO,10 Years,8.0,10 Years,3.0,10 Years,12.0,10 Years,18.0
9,18,WIPRO,5 Years,9.0,5 Years,4.0,5 Years,20.0,5 Years,17.0
10,19,WIPRO,3 Years,13.0,3 Years,0.0,3 Years,-1.0,3 Years,17.0
11,2,HDFCBANK,5 Years,22.0,5 Years,23.0,5 Years,8.0,5 Years,17.0
12,20,WIPRO,TTM,-3.0,TTM,1.0,1 Year,39.0,Last Year,14.0
13,3,HDFCBANK,3 Years,30.0,3 Years,26.0,3 Years,8.0,3 Years,17.0
14,4,HDFCBANK,TTM,47.0,TTM,27.0,1 Year,13.0,Last Year,17.0
15,5,INFY,10 Years,12.0,10 Years,9.0,10 Years,15.0,10 Years,27.0
16,6,INFY,5 Years,13.0,5 Years,11.0,5 Years,22.0,5 Years,29.0
17,7,INFY,3 Years,5.0,3 Years,10.0,3 Years,4.0,3 Years,31.0
18,8,INFY,TTM,3.0,TTM,8.0,1 Year,27.0,Last Year,32.0
19,9,SBILIFE,10 Years,23.0,10 Years,9.0,10 Years,9.0,10 Years,16.0

In [20]:
print("Missing values:")
print(analysis_clean.isna().sum())

print("\nDuplicate IDs:")
print(analysis_clean["id"].duplicated().sum())

print("\nData types:")
print(analysis_clean.dtypes)

Missing values:
id                         0
company_id                 0
sales_growth_period        0
sales_growth               0
profit_growth_period       0
profit_growth              0
stock_price_cagr_period    0
stock_price_cagr           0
roe_period                 0
roe                        0
dtype: int64

Duplicate IDs:
0

Data types:
id                           int64
company_id                  object
sales_growth_period         object
sales_growth               float64
profit_growth_period        object
profit_growth              float64
stock_price_cagr_period     object
stock_price_cagr           float64
roe_period                  object
roe                        float64
dtype: object

In [21]:
print("Sales growth < -100%:",
      (analysis_clean["sales_growth"] < -100).sum())

print("Profit growth < -100%:",
      (analysis_clean["profit_growth"] < -100).sum())

print("Stock CAGR < -100%:",
      (analysis_clean["stock_price_cagr"] < -100).sum())

print("ROE < -100%:",
      (analysis_clean["roe"] < -100).sum())

Sales growth < -100%: 0
Profit growth < -100%: 0
Stock CAGR < -100%: 0
ROE < -100%: 0

In [22]:
from pathlib import Path

CLEANED_DATA = Path(
    r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Cleaned Data"
)

CLEANED_DATA.mkdir(parents=True, exist_ok=True)

output_file = CLEANED_DATA / "nifty100_analysis_clean.csv"

analysis_clean.to_csv(
    output_file,
    index=False
)

print("Saved successfully:")
print(output_file)

Saved successfully:
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Cleaned Data\nifty100_analysis_clean.csv

In [23]:
import pandas as pd

csv_path = r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Cleaned Data\nifty100_analysis_clean.csv"

df_analysis = pd.read_csv(csv_path)

print("Shape:", df_analysis.shape)
print("Columns:")
print(df_analysis.columns.tolist())
print("\nData types:")
print(df_analysis.dtypes)
print("\nMissing values:")
print(df_analysis.isna().sum())

Shape: (20, 10)
Columns:
['id', 'company_id', 'sales_growth_period', 'sales_growth', 'profit_growth_period', 'profit_growth', 'stock_price_cagr_period', 'stock_price_cagr', 'roe_period', 'roe']

Data types:
id                           int64
company_id                  object
sales_growth_period         object
sales_growth               float64
profit_growth_period        object
profit_growth              float64
stock_price_cagr_period     object
stock_price_cagr           float64
roe_period                  object
roe                        float64
dtype: object

Missing values:
id                         0
company_id                 0
sales_growth_period        0
sales_growth               0
profit_growth_period       0
profit_growth              0
stock_price_cagr_period    0
stock_price_cagr           0
roe_period                 0
roe                        0
dtype: int64

In [24]:
import pandas as pd

analysis_path = r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Cleaned Data\nifty100_analysis_clean.csv"
companies_path = r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Cleaned Data\companies_clean.csv"

df_check = pd.read_csv(analysis_path)
df_companies = pd.read_csv(companies_path)

analysis_companies = set(df_check["company_id"].astype(str).str.strip())
company_ids = set(df_companies["id"].astype(str).str.strip())

missing_companies = sorted(analysis_companies - company_ids)

print("Analysis CSV rows:", len(df_check))
print("Companies CSV rows:", len(df_companies))
print("Missing company IDs:", missing_companies)
print("Number missing:", len(missing_companies))

Analysis CSV rows: 20
Companies CSV rows: 92
Missing company IDs: ['WIPRO']
Number missing: 1

In [25]:
wipro_rows = df_check[df_check["company_id"] == "WIPRO"]

print(wipro_rows.to_string(index=False))

 id company_id sales_growth_period  sales_growth profit_growth_period  profit_growth stock_price_cagr_period  stock_price_cagr roe_period  roe
 17      WIPRO            10 Years           8.0             10 Years            3.0                10 Years              12.0   10 Years 18.0
 18      WIPRO             5 Years           9.0              5 Years            4.0                 5 Years              20.0    5 Years 17.0
 19      WIPRO             3 Years          13.0              3 Years            0.0                 3 Years              -1.0    3 Years 17.0
 20      WIPRO                 TTM          -3.0                  TTM            1.0                  1 Year              39.0  Last Year 14.0

In [26]:
print("WIPRO in companies:", "WIPRO" in company_ids)

WIPRO in companies: False

In [27]:
import pandas as pd

raw_companies_path = r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\companies.xlsx"

raw_companies = pd.read_excel(raw_companies_path)

print("Shape:", raw_companies.shape)
print(raw_companies.columns.tolist())

print("\nWIPRO:")
print(raw_companies[
    raw_companies.astype(str).apply(
        lambda row: row.str.contains("WIPRO", case=False, na=False).any(),
        axis=1
    )
].to_string(index=False))

Shape: (93, 12)
['Mkt Fintech — Nifty 100  |  Companies  |  92 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11']

WIPRO:
Empty DataFrame
Columns: [Mkt Fintech — Nifty 100  |  Companies  |  92 records, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11]
Index: []

In [28]:
import pandas as pd

balance_path = r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Cleaned Data\balance_sheet_clean.csv"

df = pd.read_csv(balance_path)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

print("\nDuplicate company-year:",
      df.duplicated(["company_id", "year"]).sum())

print("Duplicate IDs:",
      df["id"].duplicated().sum())

print("Company-year groups with duplicates:",
      df.groupby(["company_id", "year"]).size().gt(1).sum())

# Check company IDs against master companies
companies_path = r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Cleaned Data\companies_clean.csv"

companies = pd.read_csv(companies_path)

company_ids = set(companies["id"].astype(str).str.strip())
balance_companies = set(df["company_id"].astype(str).str.strip())

print("\nCompanies missing from master:")
print(sorted(balance_companies - company_ids))

Shape: (1225, 14)
Columns: ['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets', 'debt_to_assets']

Duplicate company-year: 0
Duplicate IDs: 0
Company-year groups with duplicates: 0

Companies missing from master:
['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

In [ ]:
missing_companies = [
    "ULTRACEMCO",
    "UNIONBANK",
    "UNITDSPR",
    "VEDL",
    "WIPRO",
    "ZOMATO",
    "ZYDUSLIFE"
]

missing_rows = df[df["company_id"].isin(missing_companies)]

print("Unmatched rows:", len(missing_rows))
print("\nRows by company:")
print(missing_rows["company_id"].value_counts().sort_index())

Unmatched rows: 85

Rows by company:
company_id
ULTRACEMCO    13
UNIONBANK     12
UNITDSPR      13
VEDL          13
WIPRO         13
ZOMATO         8
ZYDUSLIFE     13
Name: count, dtype: int64

In [ ]:
print("Companies in balance sheet:", df["company_id"].nunique())
print("Companies in master:", companies["id"].nunique())

print("\nAll balance-sheet companies:")
print(sorted(df["company_id"].unique()))

print("\nAll master companies:")
print(sorted(companies["id"].unique()))

Companies in balance sheet: 98
Companies in master: 92

All balance-sheet companies:
['ABB', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'AMBUJACEM', 'APOLLOHOSP', 'ASIANPAINT', 'ATGL', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAJHLDNG', 'BAJFINANCE', 'BANKBARODA', 'BEL', 'BHARTIARTL', 'BHEL', 'BOSCHLTD', 'BPCL', 'BRITANNIA', 'CANBK', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'DABUR', 'DIVISLAB', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GODREJCP', 'GRASIM', 'HAL', 'HAVELLS', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'INDIGO', 'INDUSINDBK', 'INFY', 'IOC', 'IRCTC', 'IRFC', 'ITC', 'JINDALSTEL', 'JIOFIN', 'JSWENERGY', 'JSWSTEEL', 'KOTAKBANK', 'LICI', 'LODHA', 'LT', 'LTIM', 'M&M', 'MARUTI', 'MOTHERSON', 'NAUKRI', 'NESTLEIND', 'NHPC', 'NTPC', 'ONGC', 'PFC', 'PIDILITIND', 'PNB', 'POWERGRID', 'RECLTD', 'RELIANCE', 'SBILIFE', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SUNPHARMA', 'TATACONSUM', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TCS', 'TECHM', 'TITAN', 'TORNTPHARM', 'TRENT', 'TVSMOTOR', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

All master companies:
['ABB', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'AMBUJACEM', 'APOLLOHOSP', 'ASIANPAINT', 'ATGL', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAJHLDNG', 'BAJFINANCE', 'BANKBARODA', 'BEL', 'BHARTIARTL', 'BHEL', 'BOSCHLTD', 'BPCL', 'BRITANNIA', 'CANBK', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'DABUR', 'DIVISLAB', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GODREJCP', 'GRASIM', 'HAL', 'HAVELLS', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'INDIGO', 'INDUSINDBK', 'INFY', 'IOC', 'IRCTC', 'IRFC', 'ITC', 'JINDALSTEL', 'JIOFIN', 'JSWENERGY', 'JSWSTEEL', 'KOTAKBANK', 'LICI', 'LODHA', 'LT', 'LTIM', 'M&M', 'MARUTI', 'MOTHERSON', 'NAUKRI', 'NESTLEIND', 'NHPC', 'NTPC', 'ONGC', 'PFC', 'PIDILITIND', 'PNB', 'POWERGRID', 'RECLTD', 'RELIANCE', 'SBILIFE', 'SBIN', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SUNPHARMA', 'TATACONSUM', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TCS', 'TECHM', 'TITAN', 'TORNTPHARM', 'TRENT', 'TVSMOTOR']

In [ ]:
import pandas as pd
from pathlib import Path

cleaned = Path(
    r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Cleaned Data"
)

files = [
    "balance_sheet_clean.csv",
    "nifty100_analysis_clean.csv",
    "profit_loss_clean.csv",
    "cash_flow_clean.csv",
    "ratios_clean.csv",
    "stock_prices_clean.csv",
]

all_companies = set()

for file in files:
    path = cleaned / file

    if path.exists():
        temp = pd.read_csv(path)

        if "company_id" in temp.columns:
            ids = set(temp["company_id"].dropna().astype(str).str.strip())
            all_companies.update(ids)
            print(file, "→", len(ids), "companies")

print("\nTOTAL UNIQUE COMPANIES:", len(all_companies))
print(sorted(all_companies))

balance_sheet_clean.csv → 98 companies
nifty100_analysis_clean.csv → 5 companies
cash_flow_clean.csv → 100 companies

TOTAL UNIQUE COMPANIES: 101
['ABB', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'AGTL', 'AMBUJACEM', 'APOLLOHOSP', 'ASIANPAINT', 'ATGL', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAJHLDNG', 'BAJFINANCE', 'BANKBARODA', 'BEL', 'BHARTIARTL', 'BHEL', 'BOSCHLTD', 'BPCL', 'BRITANNIA', 'CANBK', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'DABUR', 'DIVISLAB', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GODREJCP', 'GRASIM', 'HAL', 'HAVELLS', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'INDIGO', 'INDUSINDBK', 'INFY', 'IOC', 'IRCTC', 'IRFC', 'ITC', 'JINDALSTEL', 'JIOFIN', 'JSWENERGY', 'JSWSTEEL', 'KOTAKBANK', 'LICI', 'LODHA', 'LT', 'LTIM', 'M&M', 'MARUTI', 'MOTHERSON', 'NAUKRI', 'NESTLEIND', 'NHPC', 'NTPC', 'ONGC', 'PFC', 'PIDILITIND', 'PNB', 'POWERGRID', 'RECLTD', 'RELIANCE', 'SBILIFE', 'SBIN', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SUNPHARMA', 'TATACONSUM', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TCS', 'TECHM', 'TITAN', 'TORNTPHARM', 'TRENT', 'TVSMOTOR', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

In [ ]:
master_ids = set(
    companies["id"].astype(str).str.strip()
)

all_ids = set(all_companies)

extra_ids = sorted(all_ids - master_ids)

print("Extra company IDs:", len(extra_ids))
print(extra_ids)

Extra company IDs: 9
['AGTL', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

In [ ]:
for company in extra_ids:
    print("\n", company)

    for file in [
        "balance_sheet_clean.csv",
        "nifty100_analysis_clean.csv",
        "cash_flow_clean.csv"
    ]:
        path = cleaned / file

        if path.exists():
            temp = pd.read_csv(path)

            if "company_id" in temp.columns:
                count = (temp["company_id"].astype(str).str.strip() == company).sum()

                if count > 0:
                    print("  ", file, "→", count, "rows")

 AGTL
   cash_flow_clean.csv → 7 rows

 ULTRACEMCO
   balance_sheet_clean.csv → 13 rows
   cash_flow_clean.csv → 12 rows

 UNIONBANK
   balance_sheet_clean.csv → 12 rows
   cash_flow_clean.csv → 12 rows

 UNITDSPR
   balance_sheet_clean.csv → 13 rows
   cash_flow_clean.csv → 12 rows

 VBL
   cash_flow_clean.csv → 12 rows

 VEDL
   balance_sheet_clean.csv → 13 rows
   cash_flow_clean.csv → 12 rows

 WIPRO
   balance_sheet_clean.csv → 13 rows
   nifty100_analysis_clean.csv → 4 rows
   cash_flow_clean.csv → 12 rows

 ZOMATO
   balance_sheet_clean.csv → 8 rows
   cash_flow_clean.csv → 5 rows

 ZYDUSLIFE
   balance_sheet_clean.csv → 13 rows
   cash_flow_clean.csv → 12 rows

In [ ]:
cf = pd.read_csv(
    cleaned / "cash_flow_clean.csv"
)

print(
    cf[cf["company_id"].isin(["AGTL", "ATGL"])]
    .sort_values(["company_id", "year"])
    .to_string(index=False)
)

 id company_id     year  operating_activity  investing_activity  financing_activity  net_cash_flow  company_year_count  company_year_conflict  free_cash_flow
189       AGTL Mar 2018               277.0              -988.0               779.0           68.0                   1                  False          -711.0
190       AGTL Mar 2019               356.0               791.0             -1077.0           70.0                   1                  False          1147.0
191       AGTL Mar 2020               492.0              -461.0              -102.0          -71.0                   1                  False            31.0
192       AGTL Mar 2021               654.0              -770.0                39.0          -78.0                   1                  False          -116.0
193       AGTL Mar 2022               732.0             -1133.0               422.0           21.0                   1                  False          -401.0
194       AGTL Mar 2023               853.0             -1167.0               295.0          -19.0                   1                  False          -314.0
195       AGTL Mar 2024               955.0              -752.0               -78.0          125.0                   1                  False           203.0

In [ ]:
print(
    cf[cf["company_id"] == "VBL"]
    .sort_values("year")
    .to_string(index=False)
)

  id company_id     year  operating_activity  investing_activity  financing_activity  net_cash_flow  company_year_count  company_year_conflict  free_cash_flow
1206        VBL Dec 2012               280.0              -507.0               229.0            3.0                   1                  False          -227.0
1207        VBL Dec 2013               297.0              -574.0               274.0           -2.0                   1                  False          -277.0
1208        VBL Dec 2014               431.0              -500.0                58.0          -11.0                   1                  False           -69.0
1209        VBL Dec 2015               555.0              -300.0              -236.0           19.0                   1                  False           255.0
1210        VBL Dec 2016               826.0             -1048.0               230.0            8.0                   1                  False          -222.0
1211        VBL Dec 2017               620.0              -746.0               159.0           32.0                   1                  False          -126.0
1212        VBL Dec 2018              1000.0              -937.0               -84.0          -22.0                   1                  False            63.0
1213        VBL Dec 2019              1308.0             -2320.0              1107.0           95.0                   1                  False         -1012.0
1214        VBL Dec 2020              1012.0              -472.0              -574.0          -33.0                   1                  False           540.0
1215        VBL Dec 2021              1231.0             -1008.0              -178.0           46.0                   1                  False           223.0
1216        VBL Dec 2022              1790.0             -1769.0               -18.0            4.0                   1                  False            21.0
1217        VBL Dec 2023              2391.0             -3288.0               985.0           88.0                   1                  False          -897.0

In [ ]:
from pathlib import Path

raw_data = Path(
    r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data"
)

print("Cash-flow Excel files:")

for file in raw_data.glob("*cash*flow*.xlsx"):
    print(file)

Cash-flow Excel files:
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\cashflow.xlsx

In [ ]:
for file in raw_data.rglob("*.xlsx"):
    print(file)

C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\analysis.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\balancesheet.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\cashflow.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\companies.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\documents.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\financial_ratios.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\market_cap.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\peer_groups.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\profitandloss.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\prosandcons.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\sectors.xlsx
C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\stock_prices.xlsx

In [ ]:
import pandas as pd

raw_cf_path = r"C:\Users\KIIT\OneDrive\Desktop\Financial Analytics Project\Raw Data\cashflow.xlsx"

raw_cf = pd.read_excel(raw_cf_path, header=1)

print("Shape:", raw_cf.shape)
print("Columns:", raw_cf.columns.tolist())

print("\nAGTL / ATGL records:")
print(
    raw_cf[
        raw_cf["company_id"].astype(str).str.strip().isin(["AGTL", "ATGL"])
    ].to_string(index=False)
)

Shape: (1187, 7)
Columns: ['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']

AGTL / ATGL records:
 id company_id     year  operating_activity  investing_activity  financing_activity  net_cash_flow
189       AGTL Mar 2018               277.0              -988.0               779.0           68.0
190       AGTL Mar 2019               356.0               791.0             -1077.0           70.0
191       AGTL Mar 2020               492.0              -461.0              -102.0          -71.0
192       AGTL Mar 2021               654.0              -770.0                39.0          -78.0
193       AGTL Mar 2022               732.0             -1133.0               422.0           21.0
194       AGTL Mar 2023               853.0             -1167.0               295.0          -19.0
195       AGTL Mar 2024               955.0              -752.0               -78.0          125.0